version: '3.8'
services:
 mariadb:
    image: mariadb
    container_name: my-mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: user
      MARIADB_DATABASE: my_database
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
